Pytorch IMP

In [1]:
import torch
import math

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-1.9738e+13,  4.3941e-41, -1.9738e+13,  4.3941e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.3822e-44,  4.3939e-41,  2.2790e-38,  0.0000e+00]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
ones = torch.ones(2, 3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[4.6241e+30, 1.0552e+24, 5.5757e-02],
         [1.8728e+31, 8.9683e-44, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00, 4.2661e-41],
         [0.0000e+00, 0.0000e+00, 1.4013e-45]]])
torch.Size([2, 2, 3])
tensor([[[-1.9738e+13,  4.3941e-41,  2.0180e-34],
         [ 0.0000e+00,  2.0129e-34,  0.0000e+00]],

        [[ 1.7962e-34,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  2.0124e-34,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [7]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [8]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [15]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [32]:
c = torch.rand(1, 1, 1, 1, 1) #essentially a scalar value wrapped in 5 nested arrays
print(c)

tensor([[[[[0.2030]]]]])


In [41]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.1012, 0.8093, 0.7798, 0.9667, 0.3493, 0.0047, 0.1948, 0.3617, 0.5230,
         0.4874, 0.8573, 0.9415, 0.7869, 0.2604, 0.3141, 0.1773, 0.4904, 0.9426,
         0.3553, 0.3378]])
torch.Size([20])
tensor([0.1012, 0.8093, 0.7798, 0.9667, 0.3493, 0.0047, 0.1948, 0.3617, 0.5230,
        0.4874, 0.8573, 0.9415, 0.7869, 0.2604, 0.3141, 0.1773, 0.4904, 0.9426,
        0.3553, 0.3378])
torch.Size([2, 2])
torch.Size([2, 2])


In [43]:
a = torch.rand(2,1,20)
print(a.shape)
b = a.squeeze()
print(b.shape)
a = torch.rand(2,1,20)
print(a.shape)
b = a.squeeze(0)
print(b.shape)
a = torch.rand(1,2,1,20)
print(a.shape)
b = a.squeeze()
print(b.shape)

torch.Size([2, 1, 20])
torch.Size([2, 20])
torch.Size([2, 1, 20])
torch.Size([2, 1, 20])
torch.Size([1, 2, 1, 20])
torch.Size([2, 20])
